<<<<<<< HEAD
#nO Turn
[core]
showInEditor: false
name: shikishima_temp
copyFrom: shikishima.ini
builtFrom_1_name: NONE

[movement]
moveSpeed: 0.9
maxTurnSpeed: 7
turnAcceleration: 4
moveDecelerationSpeed: 0.006
moveSlidingMode :true

[ai]
=======
#nO Turn
[core]
showInEditor: false
name: shikishima_temp
copyFrom: shikishima.ini
builtFrom_1_name: NONE

[movement]
moveSpeed: 0.9
maxTurnSpeed: 7
turnAcceleration: 4
moveDecelerationSpeed: 0.006
moveSlidingMode :true

[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
upgradedFrom: shikishima