<<<<<<< HEAD
#CC Upgrade
#ROOT:Neutrals\mercenary based units\faction specials\battlemech\BGC-BM\core\
[core]
name: NULL
class: CustomUnitMetadata
dont_load: true
=======
#CC Upgrade
#ROOT:Neutrals\mercenary based units\faction specials\battlemech\BGC-BM\core\
[core]
name: NULL
class: CustomUnitMetadata
dont_load: true
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
