<<<<<<< HEAD

[core]
@global leyteC: VIII
copyFrom: common_drone.template


#name: LeyteHead_${leyteC}
#tags: leyteT=${leyteC}

[hiddenAction_ConvertTo]
#To SHORT
=======

[core]
@global leyteC: VIII
copyFrom: common_drone.template


#name: LeyteHead_${leyteC}
#tags: leyteT=${leyteC}

[hiddenAction_ConvertTo]
#To SHORT
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
convertTo: drone_${leyteC}_SHORT