<<<<<<< HEAD
[core]
#-------------------------------
showInEditor: false
isPickableStartingUnit: true
#-------------------------------
name: 5_faction_picker_standard
displayText: Faction Picker [Standard]
displayText_ru: frakciya standard
displayText_zh: 阵营选择器 [标准]
copyFrom: faction_picker_overwriteCC.ini
=======
[core]
#-------------------------------
showInEditor: false
isPickableStartingUnit: true
#-------------------------------
name: 5_faction_picker_standard
displayText: Faction Picker [Standard]
displayText_ru: frakciya standard
displayText_zh: 阵营选择器 [标准]
copyFrom: faction_picker_overwriteCC.ini
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
