<<<<<<< HEAD
#head
[core]
name: RepairMech_UberC
showInEditor: false
copyFrom: RepairMech.ini

nanoRange: 200
nanoBuildSpeed: 1
nanoRepairSpeed: 0.9
shieldRegen: 0.3

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false

[ai]
=======
#head
[core]
name: RepairMech_UberC
showInEditor: false
copyFrom: RepairMech.ini

nanoRange: 200
nanoBuildSpeed: 1
nanoRepairSpeed: 0.9
shieldRegen: 0.3

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false

[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
upgradedFrom: RepairMech