<<<<<<< HEAD
#head
[core]
name: strider_temp
showInEditor: true
copyFrom: strider.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: strider

[movement]
=======
#head
[core]
name: strider_temp
showInEditor: true
copyFrom: strider.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: strider

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: LAND