<<<<<<< HEAD
#head
[core]
name: Apollo_vOLD_tempBuild_OrbitalDrop
showInEditor: false
copyFrom: Apollo.ini
#-------------------------------------------

#-------------------------------------------
[attachment_booster]
x: 0
y: 0
isVisible:false
idleDir:0
lockRotation:false
onCreateSpawnUnitOf: booster2
canBeAttackedAndDamaged: false
isUnselectable: true
lockLegMovement:false
canAttack:false
keepAliveWhenParentDies:false
#----------------------------
[ai]
=======
#head
[core]
name: Apollo_vOLD_tempBuild_OrbitalDrop
showInEditor: false
copyFrom: Apollo.ini
#-------------------------------------------

#-------------------------------------------
[attachment_booster]
x: 0
y: 0
isVisible:false
idleDir:0
lockRotation:false
onCreateSpawnUnitOf: booster2
canBeAttackedAndDamaged: false
isUnselectable: true
lockLegMovement:false
canAttack:false
keepAliveWhenParentDies:false
#----------------------------
[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
upgradedFrom: Apollo_vOLD