<<<<<<< HEAD
#head
[core]
name: modularMech_builder_RepMech_UberC
showInEditor: false
copyFrom: modMech_builder_RepMech.ini

nanoRange: 200
nanoBuildSpeed: 1
nanoRepairSpeed: 0.9

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false

[ai]
=======
#head
[core]
name: modularMech_builder_RepMech_UberC
showInEditor: false
copyFrom: modMech_builder_RepMech.ini

nanoRange: 200
nanoBuildSpeed: 1
nanoRepairSpeed: 0.9

[attack]

canAttack: true
canAttackFlyingUnits: false
canAttackLandUnits:   false

[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
upgradedFrom: modularMech_builder_RepMech