<<<<<<< HEAD
[core]
copyFrom: chain.template
@global number: 2

@global RockSize: 0.7

[projectile_lightning]
#This stops chaining
=======
[core]
copyFrom: chain.template
@global number: 2

@global RockSize: 0.7

[projectile_lightning]
#This stops chaining
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
spawnUnit: IGNORE