<<<<<<< HEAD
#head
[core]
name: shockie_invis
showInEditor: false
copyFrom: shockie.ini

[graphics]
isVisible: false
=======
#head
[core]
name: shockie_invis
showInEditor: false
copyFrom: shockie.ini

[graphics]
isVisible: false
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementEffect: NONE