<<<<<<< HEAD
#head
[core]
name: portal_temp_iditor
showInEditor: true
copyFrom: portal.ini
price: ${T5warpMech}
[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: portal

[movement]
=======
#head
[core]
name: portal_temp_iditor
showInEditor: true
copyFrom: portal.ini
price: ${T5warpMech}
[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: portal

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: OVER_CLIFF_WATER