<<<<<<< HEAD
#-60% movement Speed
#-65% turn speed
[core]
dont_load: true
@global portalDes: Inactive

name: portal_temp
copyFrom: portal.ini
showInEditor: true
[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: portal

[movement]
=======
#-60% movement Speed
#-65% turn speed
[core]
dont_load: true
@global portalDes: Inactive

name: portal_temp
copyFrom: portal.ini
showInEditor: true
[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: portal

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: OVER_CLIFF_WATER