<<<<<<< HEAD
#head
[core]
name: honeyBadger_temp
showInEditor: false
copyFrom: honeyBadger.ini


[hiddenAction_MechGantry]
autoTrigger: false
[hiddenAction_onCreate]
autoTriggerOnEvent: created

alsoQueueAction: MechGantryConvertToMainUnit
[hiddenAction_MechGantryConvertToMainUnit]
buildSpeed: ${mechGantryHalttimer}s
convertTo: honeyBadger

[graphics]
showQueueBar: false
[movement]
moveSpeed: 0
=======
#head
[core]
name: honeyBadger_temp
showInEditor: false
copyFrom: honeyBadger.ini


[hiddenAction_MechGantry]
autoTrigger: false
[hiddenAction_onCreate]
autoTriggerOnEvent: created

alsoQueueAction: MechGantryConvertToMainUnit
[hiddenAction_MechGantryConvertToMainUnit]
buildSpeed: ${mechGantryHalttimer}s
convertTo: honeyBadger

[graphics]
showQueueBar: false
[movement]
moveSpeed: 0
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
maxTurnSpeed: 0