<<<<<<< HEAD

[core]
@global shokaku: III
copyFrom: common_PhaseCarrierHead.template

#name: LeyteHead_${leyteC}
=======

[core]
@global shokaku: III
copyFrom: common_PhaseCarrierHead.template

#name: LeyteHead_${leyteC}
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
#tags: leyteT=${leyteC}