<<<<<<< HEAD
#head
[core]
name: tacticalMech_temp
showInEditor: true
copyFrom: Tactical_mech.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: tacticalMech

[movement]
=======
#head
[core]
name: tacticalMech_temp
showInEditor: true
copyFrom: Tactical_mech.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: tacticalMech

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: OVER_CLIFF_WATER