<<<<<<< HEAD
#head
[core]
	name: siege_tank_sm
	showInEditor: false
	copyFrom: siege tank.ini
	transportSlotsNeeded: 999
	builtFrom_1_name: NONE
    isBuilding: true
[graphics]
	animation_moving_start: 0
	animation_moving_end: 0
		movementEffect:       IGNORE
	movementEffectReverse: 	IGNORE
[ai]
=======
#head
[core]
	name: siege_tank_sm
	showInEditor: false
	copyFrom: siege tank.ini
	transportSlotsNeeded: 999
	builtFrom_1_name: NONE
    isBuilding: true
[graphics]
	animation_moving_start: 0
	animation_moving_end: 0
		movementEffect:       IGNORE
	movementEffectReverse: 	IGNORE
[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
	upgradedFrom: siege_tank