<<<<<<< HEAD

[core]
showInEditor: false
name: experimentalSpiderWidow_tempB
copyFrom: experimental_spider_temp.ini
isPickableStartingUnit: false
#startFallingWhenStartingUnit: true
builtFrom_1_name:NONE


tags: widow, assaultMech, booster, boosterOff
[graphics]
isVisible: false

[movement]
targetHeight: 1000
startingHeightOffset: 1000

=======

[core]
showInEditor: false
name: experimentalSpiderWidow_tempB
copyFrom: experimental_spider_temp.ini
isPickableStartingUnit: false
#startFallingWhenStartingUnit: true
builtFrom_1_name:NONE


tags: widow, assaultMech, booster, boosterOff
[graphics]
isVisible: false

[movement]
targetHeight: 1000
startingHeightOffset: 1000

>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
