<<<<<<< HEAD

[core]
name: missileTank_pcw
displayText: AA Missile Tank
displayText_ru: ПВА Танкега
#copyFrom:ROOT:statusEffect.template, missile_tank.ini
buildSpeed: 60s
=======

[core]
name: missileTank_pcw
displayText: AA Missile Tank
displayText_ru: ПВА Танкега
#copyFrom:ROOT:statusEffect.template, missile_tank.ini
buildSpeed: 60s
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
dont_load: true