<<<<<<< HEAD
#head
[core]
name: AT-traversalmech_temp
showInEditor: true
copyFrom: AT-traversal-mech.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: AT-traversalmech

[movement]
=======
#head
[core]
name: AT-traversalmech_temp
showInEditor: true
copyFrom: AT-traversal-mech.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: AT-traversalmech

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: LAND