<<<<<<< HEAD
#head
[core]
name: gunMech_r
showInEditor: false
copyFrom: gunMech.ini

[hiddenAction_WaterIsWet]
autoTrigger: false
[attack]
canAttack: false
isFixedFiring: false
[movement]
movementType: AIR
moveSpeed:0
targetHeight: 0
targetHeightDrift:0
maxTurnSpeed: 12
turnAcceleration: 5
[ai]
=======
#head
[core]
name: gunMech_r
showInEditor: false
copyFrom: gunMech.ini

[hiddenAction_WaterIsWet]
autoTrigger: false
[attack]
canAttack: false
isFixedFiring: false
[movement]
movementType: AIR
moveSpeed:0
targetHeight: 0
targetHeightDrift:0
maxTurnSpeed: 12
turnAcceleration: 5
[ai]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
upgradedFrom: gunMech