<<<<<<< HEAD
#head
[core]
name: vagabond_temp
showInEditor: true
copyFrom: Vagabond.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: vagabond

[movement]
=======
#head
[core]
name: vagabond_temp
showInEditor: true
copyFrom: Vagabond.ini

[hiddenAction_onCreate]
autoTriggerOnEvent: created
convertTo: vagabond

[movement]
>>>>>>> 93c300b (Потужный патч, приведение до последнего писка моды, становление на путь CE6)
movementType: OVER_CLIFF_WATER